AWSTemplateFormatVersion: "2010-09-09"
Description: "Helper system to automate climate for Tesla vehicles"

Resources:
  StateTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: name
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: name
          KeyType: HASH
